### ISSUE TITLE
Inconsistent path handling

### ISSUE THREAD

**Issue by martin-tuor** [Unity-Technologies/com.unity.formats.alembic#269]
According to line 14 in the file AlembicStreamDescriptor.cs, the path to the ABC file in the editor is handled differently than in the build:

[https://github.com/unity3d-jp/AlembicForUnity/blob/master/com.unity.formats.alembic/Runtime/Scripts/Importer/AlembicStreamDescriptor.cs#14](https://github.com/unity3d-jp/AlembicForUnity/blob/master/com.unity.formats.alembic/Runtime/Scripts/Importer/AlembicStreamDescriptor.cs#14)

As a result, the path of an imported ABC file is either not found in the editor or in the build . Since the classes are all marked as 'internal', the path can not be set on runtime either.

**Comment by mfe** [comment]
Hey @martin-tuor !

What version of the plugin are you using ?
Can you provide repro steps and the errors you get ?

I want to make sure we look at the right issue.

Thanks

**Comment by martin-tuor** [comment]
First I used the package version 1.0.4 and then downgraded to 1.0.3 because we found out, that in this version, there was no such compiler directive (`#if UNITY_EDITOR`).

We download AssetBundles and Alembic-Files from a remote server and combining them on runtime. Usually we place all downloaded files in to the **PresistentData** folder. As the deployment path of the Alembic file has to point to the **StreamingAssets** folder, we copy that file separately.

While we are testing in Unity, the path has to be something like: 
'Assets/StreamingAssets/Alembic/File.abc'

After building, the path is combined with `Application.streamingAssetsPath` by the [AlembicStreamDescriptor ](https://github.com/unity3d-jp/AlembicForUnity/blob/master/com.unity.formats.alembic/Runtime/Scripts/Importer/AlembicStreamDescriptor.cs#14) and has to be changed to:
 'Alembic/File.abc'

Otherwise, we get a FileNotFoundException as the combination will result in:
'd:/dev/project/Assets/StreamingAssets/**Assets/StreamingAssets/Alembic/File.abc**'

**Comment by JoelFortin** [comment]
Hi @martin-tuor,
We've done some work related to relative paths and a new version 1.0.5 was release yesterday ... can you upgrade and confirm if your issue is still reproducible ?

Thanks.

**Comment by martin-tuor** [comment]
I just made a small test project using the newest version 1.0.5. It seems to work properly as long as I don't **extract** the **AlembicStreamDescriptor** from the Alembic prefab (Crtl-D). 

As soon as we extract the AlembicStreamDescriptor, we are facing the same problems as before.

![Capture1](https://user-images.githubusercontent.com/46027572/57792561-93edf000-773f-11e9-9579-9a6ad21ee62d.PNG)


In order to change the location of the ABC-File after importing, I have to extract the Descriptor and change in to debug mode to set the property '**Path To Abc**'. Otherwise we are unable to download ABC-files from a server on runtime.

Another issue we experienced was, when we copy-paste an ABC-file to the StreamingAssets folder, the importer does not recognize it as an Alembic file. See screenshot:

![Capture](https://user-images.githubusercontent.com/46027572/57792480-6608ab80-773f-11e9-87c1-368f91e110fa.PNG)

**Comment by JoelFortin** [comment]
Hey @martin-tuor,
The fact that the new alembic file isn't recognized when copied in the StreamingAssets folder is normal. The StreamingAssets is a reserved folder and everything in there is meant to be interpreted at runtime, meaning that the Editor doesn't evaluate what's in there, therefore, the Alembic Exporter isn't triggered.

As for your general problem of path recognition and downloading alembic at runtime, this is definitely a limitation of the importer for now. One thing that's not clear for me is how/when you get those error in the console ? is it at build time or simply by entering in Play mode.

I tried to reproduce the setup locally on my machine, changing the "Path To Abc" that's point to a potential file that doesn't exist at the moment of building the project will simply fail to build process. At build time, the alembic needs to exist, the build step will copy the file in your Build destination and create a StreamingAssets there as well.

The current problem we have right now is that you need to setup a path in advance in Edit mode. There is no API for now so it can't be modified at runtime. If you want to risk yourself, you could use reflection and access the Descriptor class and modify the PathToAbc at runtime.

One thing for sure is that your use case is a totally legit one and we'll make sure to address this in the near future.

**Comment by martin-tuor** [comment]
>  One thing that's not clear for me is how/when you get those error in the console ? is it at build time or simply by entering in Play mode.

We get those errors by simply entering Play mode. That is, when the defined path is working in the build version. When we fix the path the way it would work in Play mode, it won't work in the build version due to the compiler directive in the [AlembicStreamDescriptor.cs (line 14)](https://github.com/unity3d-jp/AlembicForUnity/blob/master/com.unity.formats.alembic/Runtime/Scripts/Importer/AlembicStreamDescriptor.cs#14). Therefore it's hard to perform proper testing on our software.

**Comment by cguer** [comment]
Hello! In order to centralize support for the Alembic package, the Unity team has decided to close the `Issues` section of this repository.

I realize this is an old issue that should have been followed on earlier. Recent versions of the Alembic package have added the ability to point directly at files outside of the Unity project by manually adding an `Alembic Stream Player` component on any gameobject ([documentation](https://docs.unity3d.com/Packages/com.unity.formats.alembic@2.3/manual/ref_StreamPlayer.html#alembic-asset-located-outside-your-project)).

This new feature should enable the workflow listed in the current issue without having to mess with imported alembic assets.

If you still require support this issue, you can either:
- Post you question on the official [Unity Forum](https://forum.unity.com/forums/virtual-production.466/) using the `alembic` tag
- Report an issue directly inside the Unity Editor using the [Bug Report tool](https://unity.com/releases/editor/qa/bug-reporting)
