### ISSUE TITLE
Alembic vertex color animation crash

### ISSUE THREAD

**Issue by ForteDexe** [Unity-Technologies/com.unity.formats.alembic#485]
[output.zip](https://github.com/Unity-Technologies/com.unity.formats.alembic/files/7207492/output.zip)
Alembic track that have vertex color animation cause crash, while maya and other engine work fine.
Unity will crash immediately when drag the alembic track to timeline, no error log.
_Alembic package 2.2.2
_Unity version 2020.3.0f1

**Comment by ForteDexe** [comment]
[output.zip](https://github.com/Unity-Technologies/com.unity.formats.alembic/files/7207487/output.zip)

**Comment by cguer** [comment]
Hey @ForteDexe, thanks for reporting this issue! I've added the bug to our backlog for further investigation.
